### ISSUE TITLE
Project moved to other page

### ISSUE THREAD

**Issue by PANCHO7532B** [P7COMunications/panchat#1]
Hello there!
Due to "reasons", P7COMunications will no longer be updated in GitHub, project has been moved to GitLab here:

[https://gitlab.com/P7COMunications](https://gitlab.com/P7COMunications)

Check my profile for more info, but until then, this repository and organization will be abandoned indefinitely.

**Comment by PANCHO7532** [comment]
Anyway, I was able to recover my GitHub account, both repositories would be maintained regardless.
